phpstan:
  stage: test
  image: localhost:5000/php8
  cache:
    paths:
      - .composer-cache/
  before_script:
    - curl -s https://getcomposer.org/installer | php -- --filename=composer.phar
    - php composer.phar i
    - php composer.phar dump
  script:
    - php vendor/phpstan/phpstan/phpstan analyse --memory-limit 1024M -c phpstan.neon.dist --no-progress --error-format=junit > phpstan-report.xml
  after_script:
    - php vendor/phpstan/phpstan/phpstan analyse --memory-limit 1024M -c phpstan.neon.dist --no-progress
  artifacts:
    when: always
    reports:
      junit: phpstan-report.xml
    expire_in: 7 days
    paths:
      - phpstan-report.xml
  tags: ["kube-docker"]

phpunit:
  stage: test
  image: localhost:5000/php8
  cache:
    paths:
      - .composer-cache/
  before_script:
    - pecl install xdebug
    - docker-php-ext-enable xdebug
    - curl -s https://getcomposer.org/installer | php -- --filename=composer.phar
    - php composer.phar i
    - php composer.phar dump
  script:
    - XDEBUG_MODE=coverage php -n -dzend_extension=xdebug vendor/bin/phpunit tests --log-junit phpunit.junit.xml --coverage-text --colors=never
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  artifacts:
    when: always
    reports:
      junit: phpunit.junit.xml
    expire_in: 7 days
    paths:
      - phpunit.junit.xml
  tags: [ "kube-docker" ]
